import{a as q,i as p,S as b}from"./assets/vendor-b42c18af.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))l(r);new MutationObserver(r=>{for(const a of r)if(a.type==="childList")for(const u of a.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&l(u)}).observe(document,{childList:!0,subtree:!0});function n(r){const a={};return r.integrity&&(a.integrity=r.integrity),r.referrerPolicy&&(a.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?a.credentials="include":r.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function l(r){if(r.ep)return;r.ep=!0;const a=n(r);fetch(r.href,a)}})();let s,d="",i,m=null;const o={form:document.querySelector(".form"),textInput:document.querySelector("#query"),searchBtn:document.querySelector(".search-button"),galleryList:document.querySelector(".gallery-list"),searchLoader:document.querySelector(".search-loader"),moreLoader:document.querySelector(".more-loader"),moreBtn:document.querySelector(".more-button"),moreWrapper:document.querySelector(".more-wrapper")},w={captions:!0,captionDelay:250,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionClass:"",captionHTML:!0,spinner:!0};o.form.addEventListener("submit",v);async function v(e){e.preventDefault(),s=1,i=0,h(o.searchLoader),d=e.currentTarget.elements.query.value;try{const t=await f(d);i=Math.ceil(t.total/15),L(),T(t)}catch(t){console.log(t)}o.form.reset()}async function f(e){const t=new URLSearchParams({key:"42031589-0742425241f8784341d5a922f",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:s});return(await q.get(`https://pixabay.com/api/?${t}`)).data}function B({largeImageURL:e,webformatURL:t,tags:n}){return`
      <li class="gallery-item">
        <a class="gallery-link" href="${e}">
          <img
            class="gallery-image"
            src="${t}"
            data-source="${e}"
            alt="${n}"
          />
        </a>
      </li>
      `}function y(e){return e.map(B).join(`
`)}function c(e){e.classList.add("hidden")}function h(e){e.classList.remove("hidden")}function g(){o.moreWrapper.classList.add("hidden")}function P(){o.moreWrapper.classList.remove("hidden")}function L(){s<i?P():g()}function T(e){if(e.total===0){p.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),o.galleryList.innerHTML="",c(o.searchLoader);return}o.galleryList.innerHTML=y(e.hits),c(o.searchLoader),S()}function S(){m=new b(".gallery-list a",w),m.refresh()}o.moreBtn.addEventListener("click",x);async function x(e){s+1===i&&(g(),p.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),h(o.moreLoader);try{s+=1,m.destroy();const t=await f(d),n=y(t.hits);c(o.moreLoader),o.galleryList.insertAdjacentHTML("beforeend",n),H(),S()}catch(t){c(o.moreLoader),console.log(t)}}function H(){const t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
