import{a as L,i as g,S}from"./assets/vendor-b42c18af.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const a of r)if(a.type==="childList")for(const u of a.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function c(r){const a={};return r.integrity&&(a.integrity=r.integrity),r.referrerPolicy&&(a.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?a.credentials="include":r.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function n(r){if(r.ep)return;r.ep=!0;const a=c(r);fetch(r.href,a)}})();let s,d="",i,m=null;const o={form:document.querySelector(".form"),textInput:document.querySelector("#query"),searchBtn:document.querySelector(".search-button"),galleryList:document.querySelector(".gallery-list"),searchLoader:document.querySelector(".search-loader"),moreLoader:document.querySelector(".more-loader"),moreBtn:document.querySelector(".more-button"),moreWrapper:document.querySelector(".more-wrapper")},b={captions:!0,captionDelay:250,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionClass:"",captionHTML:!0,spinner:!0};o.form.addEventListener("submit",q);async function q(t){t.preventDefault(),s=1,i=null,y(o.searchLoader),d=t.currentTarget.elements.query.value;try{const e=await p(d);P(e)}catch(e){console.log(e)}o.form.reset()}async function p(t){const e=new URLSearchParams({key:"42031589-0742425241f8784341d5a922f",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:s}),n=(await L.get(`https://pixabay.com/api/?${e}`)).data;return i=Math.ceil(n.total/15),console.log(n.total),console.log("total pages: ",i),console.log("current page",s),s!=i&&v(),n}function f(t){return t.map(e=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${e.largeImageURL}">
          <img
            class="gallery-image"
            src="${e.webformatURL}"
            data-source="${e.largeImageURL}"
            alt="${e.tags}"
          />
        </a>
      </li>
      `).join(`
`)}function l(t){t.classList.add("hidden")}function y(t){t.classList.remove("hidden")}function w(){o.moreWrapper.classList.add("hidden")}function v(){o.moreWrapper.classList.remove("hidden")}function P(t){if(t.total===0){g.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),o.galleryList.innerHTML="",l(o.searchLoader);return}o.galleryList.innerHTML=f(t.hits),l(o.searchLoader),h()}function h(){m=new S(".gallery-list a",b),m.refresh()}o.moreBtn.addEventListener("click",B);async function B(t){s+1===i&&(w(),g.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),y(o.moreLoader);try{s+=1,m.destroy();const e=await p(d),c=f(e.hits);l(o.moreLoader),o.galleryList.insertAdjacentHTML("beforeend",c),M(),h()}catch(e){l(o.moreLoader),console.log(e)}}function M(){const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
