import{a as p,i as m,S as h}from"./assets/vendor-b42c18af.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const a of r)if(a.type==="childList")for(const u of a.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function i(r){const a={};return r.integrity&&(a.integrity=r.integrity),r.referrerPolicy&&(a.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?a.credentials="include":r.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function n(r){if(r.ep)return;r.ep=!0;const a=i(r);fetch(r.href,a)}})();let s,d="",c;const o={form:document.querySelector(".form"),textInput:document.querySelector("#query"),searchBtn:document.querySelector(".search-button"),galleryList:document.querySelector(".gallery-list"),searchLoader:document.querySelector(".search-loader"),moreLoader:document.querySelector(".more-loader"),moreBtn:document.querySelector(".more-button"),moreWrapper:document.querySelector(".more-wrapper")},L={captions:!0,captionDelay:250,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionClass:"",captionHTML:!0};o.form.addEventListener("submit",S);async function S(t){t.preventDefault(),s=1,c=null,f(o.searchLoader),d=t.currentTarget.elements.query.value;try{const e=await g(d);w(e)}catch(e){console.log(e)}o.form.reset()}async function g(t){const e=new URLSearchParams({key:"42031589-0742425241f8784341d5a922f",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:s}),n=(await p.get(`https://pixabay.com/api/?${e}`)).data;return c=Math.ceil(n.total/15),console.log(n.total),console.log("total pages: ",c),console.log("current page",s),s!=c&&q(),n}function y(t){return t.map(e=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${e.largeImageURL}">
          <img
            class="gallery-image"
            src="${e.webformatURL}"
            data-source="${e.largeImageURL}"
            alt="${e.tags}"
          />
        </a>
      </li>
      `).join(`
`)}function l(t){t.classList.add("hidden")}function f(t){t.classList.remove("hidden")}function b(){o.moreWrapper.classList.add("hidden")}function q(){o.moreWrapper.classList.remove("hidden")}function w(t){if(t.total===0){m.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),o.galleryList.innerHTML="",l(o.searchLoader);return}o.galleryList.innerHTML=y(t.hits),l(o.searchLoader),new h(".gallery-list a",L).refresh()}o.moreBtn.addEventListener("click",v);async function v(t){s+1===c&&(b(),m.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),f(o.moreLoader);try{s+=1;const e=await g(d),i=y(e.hits);l(o.moreLoader),o.galleryList.insertAdjacentHTML("beforeend",i),P()}catch(e){l(o.moreLoader),console.log(e)}}function P(){const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
